services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:password@db/tips
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: postgres:15.8
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tips
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

